### ISSUE TITLE
Bump androidx.security:security-crypto to final 1.1.0 version

### ISSUE THREAD

**Issue by benjohnde** [Liftric/KVault#14]
cf. https://developer.android.com/jetpack/androidx/releases/security

**Comment by distivi** [comment]
+1

As this library depends on **androidx.security:security-crypto:1.1.0-alpha03**, it has the same exception described in this thread: https://issuetracker.google.com/issues/164901843

Could you please update dependency to androidx.security:security-crypto:1.1.0-alpha05 or newer.


Stack trace:
```
com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
    at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
    at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
    at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
    at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
    at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
    at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
    at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
    at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
    at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
    at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
    at com.liftric.kvault.KVault.<init>(KVault.kt:13)
```

**Comment by benjohnde** [comment]
Going to release a new version on Monday to the latest!

**Comment by benjohnde** [comment]
Is released!
