### ISSUE TITLE
KVault initialization requires file name to change to avoid EncryptedSharedPreferences crash

### ISSUE THREAD

**Issue by cristhianescobar** [Liftric/KVault#53]
Keep running into this error that gets fix after I change the file name: so I basically have a counter that I have to update in order to fix it, do you know why this could be happening?

    single { KVault(get(), fileName = "fileName:1") }

```
0: system/security/keystore2/src/operation.rs:426: Finish failed.
                                                                                                        1: Error::Km(r#VERIFICATION_FAILED)) (public error code: 10 internal Keystore code: -30)
                                                                                                    	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:386)
                                                                                                    	at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
                                                                                                    	at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
                                                                                                    	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
                                                                                                    	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
                                                                                                    	at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
                                                                                                    	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:618)
```

**Comment by RaphaelFavero** [comment]
Any update on that issue ? I encountered the same crash.

**Comment by anox1337** [comment]
So you basically just create a new store after the old one fails?
Hmmm, there has to be a better way.

**Comment by manolodantonio** [comment]
Still present

**Comment by typ-AhmedSleem** [comment]
Got same crash also !

**Comment by Dias-Zimran** [comment]
any updates?

**Comment by gamalragab-minesec21** [comment]
@cristhianescobar 

u can do that 
it's working with me 

internal actual fun Scope.createPlatformKVaultStore(): KVault {
    val context = androidContext()
    return try {
        KVault(context, DATASTORE_FILE_NAME)
    } catch (e: Exception) {
        // Clean and recreate to avoid crash after reinstall
        context.deleteSharedPreferences(DATASTORE_FILE_NAME)
        KVault(context, DATASTORE_FILE_NAME)
    }
}
